<?php

namespace App\Console\Commands;

use App\Enums\DocumentType;
use App\Models\Document;
use App\Models\DocumentVersion;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

/**
 * Re-writes every stored demo PDF with a freshly generated, valid document.
 *
 * Earlier seeds produced malformed PDFs (wrong /Length, no xref), so inline
 * preview showed "Failed to load PDF document". This command repairs existing
 * rows without touching the database, so an already-seeded demo keeps working.
 */
class RegenerateDemoDocuments extends Command
{
    protected $signature = 'sakha:regenerate-documents {--dry-run : Report only, write nothing}';

    protected $description = 'Regenerate stored demo document PDFs so they are valid and viewable.';
    public function handle(): int
    {
        $dryRun = (bool) $this->option('dry-run');
        $disk = Storage::disk('local');

        $documents = Document::query()->with('transaction')->get();
        $this->info(($dryRun ? '[dry-run] ' : '').'Documents to process: '.$documents->count());

        $repaired = 0;
        $skipped = 0;

        foreach ($documents as $document) {
            if (! $document->transaction) {
                $skipped++;
                continue;
            }

            /** @var DocumentType $type */
            $type = $document->document_type;
            $pdf = $this->renderPdf($document->transaction->transaction_code, $type->label());

            if (! $dryRun) {
                $disk->put($document->file_path, $pdf);
                $document->forceFill(['file_size' => strlen($pdf), 'mime_type' => 'application/pdf'])->save();

                DocumentVersion::query()
                    ->where('document_id', $document->id)
                    ->update(['file_size' => strlen($pdf)]);
            }

            $repaired++;
        }

        $this->info("Repaired: {$repaired}  Skipped: {$skipped}");

        return self::SUCCESS;
    }

    /**
     * Build a valid single-page PDF with a small, readable layout.
     */
    private function renderPdf(string $code, string $label): string
    {
        $esc = static fn (string $s): string => str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $s);

        $title = $esc('SAKHA - '.$label);
        $reference = $esc($code);
        $stamp = $esc(now()->format('d M Y H:i'));

        $stream = "BT\n"
            ."/F2 18 Tf 0.06 0.09 0.16 rg 72 720 Td ({$title}) Tj ET\n"
            ."BT\n/F1 11 Tf 0.35 0.40 0.48 rg 72 700 Td (Document reference: {$reference}) Tj ET\n"
            ."BT\n/F1 11 Tf 0.35 0.40 0.48 rg 72 684 Td (Generated: {$stamp}) Tj ET\n"
            ."0.90 0.92 0.95 RG 1 w 72 664 m 540 664 l S\n"
            ."BT\n/F1 12 Tf 0.15 0.18 0.24 rg 72 636 Td (This is a DEMO placeholder document generated by the) Tj ET\n"
            ."BT\n/F1 12 Tf 0.15 0.18 0.24 rg 72 618 Td (SAKHA Finance Operations prototype. It contains no company data.) Tj ET\n";

        $objects = [];
        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
        $objects[2] = '<< /Type /Pages /Kids [3 0 R] /Count 1 >>';
        $objects[3] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] '
            .'/Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>';
        $objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
        $objects[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';
        $objects[6] = '<< /Length '.strlen($stream)." >>\nstream\n".$stream.'endstream';

        $pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
        $offsets = [];
        foreach ($objects as $num => $body) {
            $offsets[$num] = strlen($pdf);
            $pdf .= "{$num} 0 obj\n{$body}\nendobj\n";
        }

        $xrefOffset = strlen($pdf);
        $count = count($objects) + 1;
        $pdf .= "xref\n0 {$count}\n";
        $pdf .= "0000000000 65535 f \n";
        for ($i = 1; $i <= count($objects); $i++) {
            $pdf .= str_pad((string) $offsets[$i], 10, '0', STR_PAD_LEFT)." 00000 n \n";
        }
        $pdf .= "trailer\n<< /Size {$count} /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }
}
